server:
  port: 7070

spring:
  application:
    name: charity-management-system
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: "optional:file:.env[.properties]"

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000